name: CMake

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build-macos:
    runs-on: macos-10.15
    steps:
      - name: Check out code
        uses: actions/checkout@main
        
      - name: Install Packages
        working-directory: ${{github.workspace}}/
        run: ./Script/compile_bullet.sh

      - name: Install Packages
        working-directory: ${{github.workspace}}/
        run: ./Script/compile_box2d.sh

      - name: Install Packages
        working-directory: ${{github.workspace}}/
        run: ./Script/compile_box2d.sh

      - name: Build
        shell: bash
        working-directory: ${{github.workspace}}/
        run: ./Script/compile_mac.sh

  build-win10:
    runs-on: windows-2019
    steps:
      - name: Check out code
        uses: actions/checkout@main
      
      - name: Install Packages
        working-directory: ${{github.workspace}}/
        run: ./Script/compile_bullet.sh

      - name: Build
        shell: bash
        working-directory: ${{github.workspace}}/
        run: ./Script/compile_win.sh
      
  build-ubuntu:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out code
        uses: actions/checkout@main
        
      - name: Install Packages
        working-directory: ${{github.workspace}}/
        run: ./Script/compile_bullet.sh

      - name: Install Packages
        working-directory: ${{github.workspace}}/
        run: ./Script/compile_box2d.sh

      - name: Install Packages
        working-directory: ${{github.workspace}}/
        run: ./Script/compile_box2d.sh

      - name: Build
        shell: bash
        working-directory: ${{github.workspace}}/
        run: ./Script/compile_linux.sh